=begin
#Neblio REST API Suite

#APIs for Interacting with NTP1 Tokens & The Neblio Blockchain

OpenAPI spec version: 1.1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::IssueTokenResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IssueTokenResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::IssueTokenResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IssueTokenResponse' do
    it 'should create an instance of IssueTokenResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::IssueTokenResponse)
    end
  end
  describe 'test attribute "token_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tx_hex"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

