=begin
#Neblio REST API Suite

#APIs for Interacting with NTP1 Tokens & The Neblio Blockchain

OpenAPI spec version: 1.2.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-SNAPSHOT

=end

# Common files
require 'neblio_api/api_client'
require 'neblio_api/api_error'
require 'neblio_api/version'
require 'neblio_api/configuration'

# Models
require 'neblio_api/models/broadcast_tx_request'
require 'neblio_api/models/broadcast_tx_response'
require 'neblio_api/models/burn_token_request'
require 'neblio_api/models/burn_token_request_burn'
require 'neblio_api/models/burn_token_response'
require 'neblio_api/models/error'
require 'neblio_api/models/get_address_info_response'
require 'neblio_api/models/get_address_info_response_tokens'
require 'neblio_api/models/get_address_info_response_utxos'
require 'neblio_api/models/get_address_response'
require 'neblio_api/models/get_block_index_response'
require 'neblio_api/models/get_block_response'
require 'neblio_api/models/get_faucet_response'
require 'neblio_api/models/get_faucet_response_data'
require 'neblio_api/models/get_raw_tx_response'
require 'neblio_api/models/get_sync_response'
require 'neblio_api/models/get_token_holders_response'
require 'neblio_api/models/get_token_holders_response_holders'
require 'neblio_api/models/get_token_id_response'
require 'neblio_api/models/get_token_metadata_response'
require 'neblio_api/models/get_token_metadata_response_metadata_of_issuence'
require 'neblio_api/models/get_token_metadata_response_metadata_of_issuence_data'
require 'neblio_api/models/get_token_metadata_response_metadata_of_issuence_data_user_data'
require 'neblio_api/models/get_token_metadata_response_metadata_of_issuence_data_user_data_meta'
require 'neblio_api/models/get_transaction_info_response'
require 'neblio_api/models/get_transaction_info_response_previous_output'
require 'neblio_api/models/get_transaction_info_response_script_sig'
require 'neblio_api/models/get_transaction_info_response_tokens'
require 'neblio_api/models/get_transaction_info_response_vin'
require 'neblio_api/models/get_transaction_info_response_vout'
require 'neblio_api/models/get_tx_response'
require 'neblio_api/models/get_tx_response_vin'
require 'neblio_api/models/get_tx_response_vout'
require 'neblio_api/models/get_txs_response'
require 'neblio_api/models/issue_token_request'
require 'neblio_api/models/issue_token_request_flags'
require 'neblio_api/models/issue_token_request_metadata'
require 'neblio_api/models/issue_token_request_metadata_encryptions'
require 'neblio_api/models/issue_token_request_metadata_rules'
require 'neblio_api/models/issue_token_request_metadata_rules_expiration'
require 'neblio_api/models/issue_token_request_metadata_rules_fees'
require 'neblio_api/models/issue_token_request_metadata_rules_fees_items'
require 'neblio_api/models/issue_token_request_metadata_rules_holders'
require 'neblio_api/models/issue_token_request_metadata_urls'
require 'neblio_api/models/issue_token_request_transfer'
require 'neblio_api/models/issue_token_response'
require 'neblio_api/models/rpc_request'
require 'neblio_api/models/rpc_response'
require 'neblio_api/models/send_token_request'
require 'neblio_api/models/send_token_request_to'
require 'neblio_api/models/send_token_response'
require 'neblio_api/models/send_tx_request'

# APIs
require 'neblio_api/api/insight_api'
require 'neblio_api/api/jsonrpc_api'
require 'neblio_api/api/ntp1_api'
require 'neblio_api/api/testnet_faucet_api'
require 'neblio_api/api/testnet_insight_api'
require 'neblio_api/api/testnet_ntp1_api'

module NeblioAPI
  class << self
    # Customize default settings for the SDK using block.
    #   NeblioAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
