=begin
#Neblio REST API Suite

#APIs for Interacting with NTP1 Tokens & The Neblio Blockchain

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/broadcast_tx_request'
require 'swagger_client/models/broadcast_tx_response'
require 'swagger_client/models/burn_token_request'
require 'swagger_client/models/burn_token_request_burn'
require 'swagger_client/models/burn_token_response'
require 'swagger_client/models/error'
require 'swagger_client/models/get_address_info_response'
require 'swagger_client/models/get_address_info_response_tokens'
require 'swagger_client/models/get_address_info_response_utxos'
require 'swagger_client/models/get_token_holders_response'
require 'swagger_client/models/get_token_holders_response_holders'
require 'swagger_client/models/get_token_id_response'
require 'swagger_client/models/get_token_metadata_response'
require 'swagger_client/models/get_token_metadata_response_metadata_of_issuance'
require 'swagger_client/models/get_token_metadata_response_metadata_of_issuance_data'
require 'swagger_client/models/get_token_metadata_response_metadata_of_issuance_data_user_data'
require 'swagger_client/models/get_token_metadata_response_metadata_of_issuance_data_user_data_meta'
require 'swagger_client/models/issue_token_request'
require 'swagger_client/models/issue_token_request_metadata'
require 'swagger_client/models/issue_token_request_metadata_encryptions'
require 'swagger_client/models/issue_token_request_metadata_rules'
require 'swagger_client/models/issue_token_request_metadata_rules_expiration'
require 'swagger_client/models/issue_token_request_metadata_rules_fees'
require 'swagger_client/models/issue_token_request_metadata_rules_fees_items'
require 'swagger_client/models/issue_token_request_metadata_rules_holders'
require 'swagger_client/models/issue_token_request_metadata_urls'
require 'swagger_client/models/issue_token_response'
require 'swagger_client/models/send_token_request'
require 'swagger_client/models/send_token_request_to'
require 'swagger_client/models/send_token_response'

# APIs
require 'swagger_client/api/ntp1_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
