=begin
#Neblio REST API Suite

#APIs for Interacting with NTP1 Tokens & The Neblio Blockchain

OpenAPI spec version: 1.3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

module NeblioAPI
  VERSION = '1.2.1'
end
